### ISSUE TITLE
issues with the v1.0.0-beta

### ISSUE THREAD

**Issue by expansing** [jontofront/ecoNET-300-Home-Assistant-Integration#54]
Hi,

The HA just poped an update for the v1.0.0-beta update. Yes I have beta updates on. Very interested in your development.
Removed the old version as instructed and installed the new beta.
Found a couple of issues.
This ones are reported by the HA.

```
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 7:26:11 AM (2 occurrences)
Last logged: 7:36:28 AM

Unable to prepare setup for platform 'econet300.number': Platform not found (Exception importing custom_components.econet300.number).

```
```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 7:26:11 AM (2 occurrences)
Last logged: 7:36:28 AM

Unexpected exception importing platform custom_components.econet300.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/econet300/number.py", line 23, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument '_attr_native_step' follows default argument
```
Also:
Many sensors will not display the correct data.

Regards,
Cornel

**Comment by jontofront** [comment]
@expansing 
Thanks we will debug it

**Comment by AlexSyxar** [comment]
Hello. First of all many thanks for the integration development
Just a small feedback.
In ver 0.33 all sensors are ok but in all Betas they are unavailable (device model and fw are on screenshot)
![econet integr](https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/assets/157969427/28a8de69-0564-4ce4-b92d-c625b0d5abe8)

PS is there any possibility in the future to control a device? For example to turn in on/off, change "set temperature"?

Thanks in advance

**Comment by jontofront** [comment]
yes, we rewrite the new version, in this version need to reinstall all entities. I mean delete integartion and reinstall. We working on that.
Yes if you want new feature please request it opneed new ticket.

**Comment by AlexSyxar** [comment]
Unfortunately even after complete uninstallation and reinstallation version 1.0.0 beta10 doesn't see any devices, after downgrading (just redownloading without deinstallation) to 0.3.3 all devs appears immediately

**Comment by jontofront** [comment]
can you send me errors from error log?

**Comment by AlexSyxar** [comment]
Sure. How it can be collected?
