### ISSUE TITLE
master-1.0.0-beta errors and can't set temperature

### ISSUE THREAD

**Issue by jontofront** [jontofront/ecoNET-300-Home-Assistant-Integration#55]
`2024-01-28 21:34:55.512 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform econet300
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
if self.config_entry and (device_info := entity.device_info):
^^^^^^^^^^^^^^^^^^
File "/config/custom_components/econet300/entity.py", line 110, in device_info
identifiers={(DOMAIN, f"{self._api.uid()}-mixer-{self._idx}")},
^^^^^^^^^
AttributeError: 'MixerSensor' object has no attribute '_api'
2024-01-28 21:34:55.653 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up econet300 platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
if self.config_entry and (device_info := entity.device_info):
^^^^^^^^^^^^^^^^^^
File "/config/custom_components/econet300/entity.py", line 110, in device_info
identifiers={(DOMAIN, f"{self._api.uid()}-mixer-{self._idx}")},
^^^^^^^^^
AttributeError: 'MixerSensor' object has no attribute '_api'`

![image](https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/assets/37038426/6aef7b83-bf98-47a4-b0c6-ea304a751c90)

![image](https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/assets/37038426/c13768ab-0af2-49e8-8296-e17cddfef562)

**Comment by AkiraJager** [comment]
@jontofront  updated BRANCH
