### ISSUE TITLE
[Bug]: fix value types and add STATE for Mixer1 

### ISSUE THREAD

**Issue by jontofront** [jontofront/ecoNET-300-Home-Assistant-Integration#75]
### The request

**fix error**
`2024-10-15 22:17:24.686 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 657, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Off'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 660, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Off'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/econet300/entity.py", line 62, in _handle_coordinator_update
    self._sync_state(value)
  File "/config/custom_components/econet300/sensor.py", line 68, in _sync_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.plum_econet300_mixer_1_servo_position has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'Off' (<class 'str'>)`

**Add HA constants**

const.py  https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/blob/b0645cf083fb23b2844aa82acb1cd3cdb186a00f/custom_components/econet300/const.py#L328

[/homeassistant/const.py](https://github.com/home-assistant/core/blob/ef89d1cd3de01414c9effe604e02431397e02cf2/homeassistant/const.py#L338)
STATE_OFF: Final = "off"
STATE_OPENING: Final = "opening"
STATE_CLOSING: Final = "closing"

**Comment by jontofront** [comment]
https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration/commit/b7177de6f6790bd0151bde6d440b894050a2c56b
